services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    env_file:
      - ./apartment-booking-api/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"  # Uses the port from .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 
