import { Prisma } from '@prisma/client';

// create type without owner to use owner in seeds file
export type ApartmentSeedData = Omit<Prisma.ApartmentCreateInput, 'owner'>;

export const apartmentData: ApartmentSeedData[] = [
  {
    unitName: 'Luxury Apartment',
    unitNumber: 'A101',
    project: 'Downtown Heights',
    description: 'A beautiful luxury apartment in the heart of downtown.',
    price: 2500.00,
    location: 'Downtown',
    bedrooms: 3,
    bathrooms: 2,
    area: 150.5,
    available: true,
    features: ['Balcony', 'Pool', 'Gym', 'Parking'],
    images: [],
  },
  {
    unitName: 'Cozy Studio',
    unitNumber: 'B202',
    project: 'Urban Living',
    description: 'A cozy studio apartment perfect for singles or couples.',
    price: 1200.00,
    location: 'Midtown',
    bedrooms: 1,
    bathrooms: 1,
    area: 65.0,
    available: true,
    features: ['Furnished', 'Air Conditioning', 'Security System'],
    images: [],
  },
  {
    unitName: 'Family Townhouse',
    unitNumber: 'C303',
    project: 'Suburban Paradise',
    description: 'A spacious townhouse perfect for families.',
    price: 3200.00,
    location: 'Suburbs',
    bedrooms: 4,
    bathrooms: 3,
    area: 220.0,
    available: true,
    features: ['Garden', 'Garage', 'Fireplace', 'Basement'],
    images: [],
  },
  {
    unitName: 'Modern Loft',
    unitNumber: 'D404',
    project: 'Industrial Chic',
    description: 'A modern loft with industrial design elements.',
    price: 1800.00,
    location: 'Arts District',
    bedrooms: 2,
    bathrooms: 2,
    area: 110.0,
    available: true,
    features: ['High Ceilings', 'Exposed Brick', 'Stainless Steel Appliances'],
    images: [],
  },
  {
    unitName: 'Penthouse Suite',
    unitNumber: 'E505',
    project: 'Skyline Towers',
    description: 'A luxurious penthouse with panoramic city views.',
    price: 5000.00,
    location: 'Downtown',
    bedrooms: 4,
    bathrooms: 3,
    area: 300.0,
    available: true,
    features: ['Private Terrace', 'Hot Tub', 'Wine Cellar', 'Home Theater'],
    images: [],
  },
  {
    unitName: 'Garden Apartment',
    unitNumber: 'F606',
    project: 'Green Living',
    description: 'A ground-floor apartment with a private garden.',
    price: 2200.00,
    location: 'Residential District',
    bedrooms: 2,
    bathrooms: 2,
    area: 120.0,
    available: true,
    features: ['Private Garden', 'Patio', 'Outdoor Kitchen'],
    images: [],
  },
  {
    unitName: 'Beachfront Condo',
    unitNumber: 'G707',
    project: 'Ocean View',
    description: 'A beautiful condo with direct beach access.',
    price: 3800.00,
    location: 'Beachfront',
    bedrooms: 3,
    bathrooms: 2,
    area: 180.0,
    available: true,
    features: ['Ocean View', 'Private Beach Access', 'Balcony'],
    images: [],
  },
  {
    unitName: 'Mountain Cabin',
    unitNumber: 'H808',
    project: 'Alpine Retreat',
    description: 'A cozy cabin with stunning mountain views.',
    price: 2800.00,
    location: 'Mountain Range',
    bedrooms: 3,
    bathrooms: 2,
    area: 160.0,
    available: true,
    features: ['Fireplace', 'Wooden Deck', 'Hiking Trails'],
    images: [],
  },
  {
    unitName: 'Student Studio',
    unitNumber: 'I909',
    project: 'Campus Living',
    description: 'A compact studio apartment near the university.',
    price: 800.00,
    location: 'University District',
    bedrooms: 1,
    bathrooms: 1,
    area: 40.0,
    available: true,
    features: ['Study Desk', 'High-Speed Internet', 'Laundry Facilities'],
    images: [],
  },
  {
    unitName: 'Executive Suite',
    unitNumber: 'J1010',
    project: 'Business Center',
    description: 'A premium apartment for business professionals.',
    price: 3500.00,
    location: 'Financial District',
    bedrooms: 2,
    bathrooms: 2,
    area: 140.0,
    available: true,
    features: ['Home Office', 'Conference Room Access', 'Concierge Service'],
    images: [],
  },
  {
    unitName: 'Artist Loft',
    unitNumber: 'K1111',
    project: 'Creative Commons',
    description: 'A spacious loft designed for artists and creators.',
    price: 1600.00,
    location: 'Arts District',
    bedrooms: 1,
    bathrooms: 1,
    area: 90.0,
    available: true,
    features: ['Studio Space', 'North-Facing Windows', 'Utility Sink'],
    images: [],
  },
  {
    unitName: 'Family Apartment',
    unitNumber: 'L1212',
    project: 'Family First',
    description: 'A comfortable apartment designed for families with children.',
    price: 2700.00,
    location: 'Suburban Area',
    bedrooms: 3,
    bathrooms: 2,
    area: 170.0,
    available: true,
    features: ['Playground Access', 'Child-Safe Features', 'Storage Space'],
    images: [],
  },
  {
    unitName: 'Senior Living Unit',
    unitNumber: 'M1313',
    project: 'Golden Years',
    description: 'A thoughtfully designed apartment for senior living.',
    price: 2300.00,
    location: 'Quiet Neighborhood',
    bedrooms: 2,
    bathrooms: 2,
    area: 130.0,
    available: true,
    features: ['Accessibility Features', 'Emergency Call System', 'Community Activities'],
    images: [],
  },
  {
    unitName: 'Eco-Friendly Apartment',
    unitNumber: 'N1414',
    project: 'Green Living',
    description: 'A sustainable apartment with eco-friendly features.',
    price: 2400.00,
    location: 'Green District',
    bedrooms: 2,
    bathrooms: 2,
    area: 125.0,
    available: true,
    features: ['Solar Panels', 'Rainwater Collection', 'Energy-Efficient Appliances'],
    images: [],
  },
  {
    unitName: 'Historic Brownstone',
    unitNumber: 'O1515',
    project: 'Heritage Row',
    description: 'A charming apartment in a restored historic building.',
    price: 2900.00,
    location: 'Historic District',
    bedrooms: 2,
    bathrooms: 1,
    area: 135.0,
    available: true,
    features: ['Original Hardwood Floors', 'Ornate Moldings', 'Fireplace'],
    images: [],
  },
  {
    unitName: 'Smart Home Apartment',
    unitNumber: 'P1616',
    project: 'Tech Living',
    description: 'A modern apartment with integrated smart home technology.',
    price: 2600.00,
    location: 'Tech Hub',
    bedrooms: 2,
    bathrooms: 2,
    area: 120.0,
    available: true,
    features: ['Voice Control', 'Smart Lighting', 'Automated Climate Control'],
    images: [],
  },
  {
    unitName: 'Waterfront Apartment',
    unitNumber: 'Q1717',
    project: 'Harbor View',
    description: 'A stunning apartment with views of the harbor.',
    price: 3300.00,
    location: 'Harbor District',
    bedrooms: 3,
    bathrooms: 2,
    area: 175.0,
    available: true,
    features: ['Water View', 'Private Dock Access', 'Balcony'],
    images: [],
  },
  {
    unitName: 'Pet-Friendly Condo',
    unitNumber: 'R1818',
    project: 'Paws & Relax',
    description: 'A comfortable condo designed for pet owners.',
    price: 2100.00,
    location: 'Park Adjacent',
    bedrooms: 2,
    bathrooms: 2,
    area: 115.0,
    available: true,
    features: ['Pet Washing Station', 'Nearby Dog Park', 'Scratch-Resistant Flooring'],
    images: [],
  },
  {
    unitName: 'Minimalist Studio',
    unitNumber: 'S1919',
    project: 'Less is More',
    description: 'A sleek, minimalist studio with efficient design.',
    price: 1400.00,
    location: 'Design District',
    bedrooms: 1,
    bathrooms: 1,
    area: 55.0,
    available: true,
    features: ['Built-in Storage', 'Convertible Furniture', 'Clean Lines'],
    images: [],
  },
  {
    unitName: 'Luxury Villa',
    unitNumber: 'T2020',
    project: 'Elite Estates',
    description: 'An exclusive villa with premium amenities and privacy.',
    price: 6000.00,
    location: 'Exclusive Neighborhood',
    bedrooms: 5,
    bathrooms: 4,
    area: 350.0,
    available: true,
    features: ['Private Pool', 'Home Gym', 'Wine Cellar', 'Security System'],
    images: [],
  }
];